name: bluetooth_low_energy_linux
description: Linux implementation of the bluetooth_low_energy plugin.
version: 5.0.2
homepage: https://github.com/yanshouwang/bluetooth_low_energy

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface:
    git:
      url: https://github.com/nsNeruno/bluetooth_low_energy.git
      path: bluetooth_low_energy_platform_interface
      ref: legacy

  bluez: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: bluetooth_low_energy
    platforms:
      linux:
        dartPluginClass: BluetoothLowEnergyLinux
