name: bluetooth_low_energy
description: A Flutter plugin for controlling the bluetooth low energy, supports central and peripheral apis.
version: 5.0.7
homepage: https://github.com/yanshouwang/bluetooth_low_energy

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface:
    git:
      url: https://github.com/nsNeruno/bluetooth_low_energy.git
      path: bluetooth_low_energy_platform_interface
      ref: legacy
  bluetooth_low_energy_android:
    git:
      url: https://github.com/nsNeruno/bluetooth_low_energy.git
      path: bluetooth_low_energy_android
      ref: legacy
  bluetooth_low_energy_darwin:
    git:
      url: https://github.com/nsNeruno/bluetooth_low_energy.git
      path: bluetooth_low_energy_darwin
      ref: legacy
  bluetooth_low_energy_windows:
    git:
      url: https://github.com/nsNeruno/bluetooth_low_energy.git
      path: bluetooth_low_energy_windows
      ref: legacy
  bluetooth_low_energy_linux:
    git:
      url: https://github.com/nsNeruno/bluetooth_low_energy.git
      path: bluetooth_low_energy_linux
      ref: legacy

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: bluetooth_low_energy_android
      ios:
        default_package: bluetooth_low_energy_darwin
      macos:
        default_package: bluetooth_low_energy_darwin
      windows:
        default_package: bluetooth_low_energy_windows
      linux:
        default_package: bluetooth_low_energy_linux
