name: bluetooth_low_energy_platform_interface
description: A common platform interface for the bluetooth_low_energy plugin.
version: 5.0.2
homepage: https://github.com/yanshouwang/bluetooth_low_energy

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  log_service:
    git:
      url: https://github.com/nsNeruno/log_service.git
      ref: legacy

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
